# Uncomment the next line to define a global platform for your project
# platform :ios, '15.5'

target 'SpotifyLoginSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpotifyLoginSampleApp

  pod 'Firebase/Auth'         # 파이어베이스
  pod 'GoogleSignIn', '5.0.2' # 구글 로그인

end
